# Generated by Django 3.0.5 on 2023-07-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIN', models.CharField(max_length=200, null=True, unique=True)),
                ('Type', models.CharField(choices=[('Universitaire', 'Universitaire'), ('Administratif', 'Administratif'), ('Commercial', 'Commercial')], max_length=200, null=True)),
                ('Prenom_v', models.CharField(max_length=200, null=True)),
                ('Nom_V', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
